version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

  db:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: ["sh", "-c", "mkdir -p /data && touch /data/oven.db && tail -f /dev/null"]

volumes:
  data: